credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: stauth.Hasher(['abc', 'def']).generate()
    rbriggs:
      email: rbriggs@gmail.com
      name: Jane Doe
      password: stauth.Hasher(['abc', 'def']).generate()
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - lcbean6@gmail.com
